# Generated by Django 3.1.6 on 2021-02-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=120, verbose_name='First And Last Name')),
                ('dateofbirth', models.DateField(verbose_name='Date Of Birth')),
                ('phone', models.IntegerField(unique=True, verbose_name='Phone Number')),
                ('idcode', models.IntegerField(max_length=10, unique=True, verbose_name='ID Code')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is Admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='is Active')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
