# Generated by Django 3.1.7 on 2021-03-10 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='Email')),
                ('email_confirm', models.BooleanField(default=False, verbose_name='Email Confirm')),
                ('full_name', models.CharField(max_length=120, verbose_name='First And Last Name')),
                ('dateofbirth', models.DateField(verbose_name='Date Of Birth')),
                ('phone', models.IntegerField(unique=True, verbose_name='Phone Number')),
                ('phone_confirm', models.BooleanField(default=False, verbose_name='Phone Confirm')),
                ('idcode', models.CharField(max_length=10, unique=True, verbose_name='ID Code')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is Admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='is Active')),
                ('joindate', models.DateTimeField(auto_now=True, verbose_name='Join Date')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='ConfirmCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_code', models.IntegerField(blank=True, null=True, verbose_name='Email Code')),
                ('phone_code', models.IntegerField(blank=True, null=True, verbose_name='Phone Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Confirm Code',
                'verbose_name_plural': 'Confirm Codes',
            },
        ),
    ]
