# Generated by Django 3.1.6 on 2021-02-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idcode',
            field=models.IntegerField(unique=True, verbose_name='ID Code'),
        ),
    ]
