# Generated by Django 3.1.7 on 2021-03-03 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210221_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirm',
            field=models.BooleanField(default=False, verbose_name='Email Confirm'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_confirm',
            field=models.BooleanField(default=False, verbose_name='Phone Confirm'),
        ),
        migrations.CreateModel(
            name='ConfirmCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_code', models.IntegerField(verbose_name='Email Code')),
                ('phone_code', models.IntegerField(verbose_name='Phone Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_code', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Confirm Code',
                'verbose_name_plural': 'Confirm Codes',
            },
        ),
    ]
