# Generated by Django 3.1.7 on 2021-03-03 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210303_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_code', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
