# Generated by Django 3.1.6 on 2021-03-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210303_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idcode',
            field=models.CharField(max_length=10, unique=True, verbose_name='ID Code'),
        ),
    ]
