# Generated by Django 3.1.7 on 2021-03-05 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210304_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
