# Generated by Django 3.1.7 on 2021-03-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210305_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joindate',
            field=models.DateTimeField(auto_now=True, verbose_name='Join Date'),
        ),
    ]
