# Generated by Django 3.1.7 on 2021-03-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmcode',
            name='email_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Email Code'),
        ),
        migrations.AlterField(
            model_name='confirmcode',
            name='phone_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Code'),
        ),
    ]
