# Generated by Django 3.1.7 on 2021-03-10 16:27

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head1', models.CharField(max_length=120, verbose_name='Head 1')),
                ('head1_text', models.CharField(blank=True, max_length=120, null=True, verbose_name='Text Head 1')),
                ('head2', models.CharField(max_length=200, verbose_name='Head 2')),
                ('head2_text', models.CharField(blank=True, max_length=120, null=True, verbose_name='Text Head 2')),
                ('head3', models.CharField(max_length=120, verbose_name='Head 3')),
                ('head3_text', models.CharField(blank=True, max_length=120, null=True, verbose_name='Text Head 3')),
                ('img', models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Image')),
                ('img_head', models.CharField(max_length=200, verbose_name='Image Head')),
                ('img_text', models.TextField(verbose_name='Image Text')),
                ('plain_text', models.TextField(verbose_name='Plain Text')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('Read', 'Read'), ('UnRead', 'UnRead')], default='UnRead', max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Contact us',
                'verbose_name_plural': 'Contact us',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone')),
                ('head', models.CharField(max_length=200, verbose_name='Contact Us Head')),
                ('logo', models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Logo')),
                ('fb', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook link')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='twitter link')),
                ('ln', models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn link')),
                ('google', models.CharField(blank=True, max_length=200, null=True, verbose_name='G+ link')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Footer Control',
                'verbose_name_plural': 'Footer Control',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Logo')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Header Control',
                'verbose_name_plural': 'Header Control',
            },
        ),
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('joindate', models.DateTimeField(auto_now_add=True, verbose_name='Join Date')),
            ],
            options={
                'verbose_name': 'Newsletters',
                'verbose_name_plural': 'Newsletters',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head1', models.CharField(max_length=200, verbose_name='Head 1')),
                ('head2', models.CharField(max_length=200, verbose_name='Head 2')),
                ('head2_text', models.CharField(blank=True, max_length=120, null=True, verbose_name='Text Head 2')),
                ('proj_total', models.IntegerField(verbose_name='Total Projects')),
                ('proj_done', models.IntegerField(verbose_name='Projects Done')),
                ('img', models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Image')),
                ('img_head', models.CharField(max_length=200, verbose_name='Image Head')),
                ('img_text', models.TextField(verbose_name='Image Text')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Service Page',
                'verbose_name_plural': 'Services Page',
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Profile Inmage')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('bio', models.CharField(max_length=200, verbose_name='Bio')),
                ('fb', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook link')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='twitter link')),
                ('ln', models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn link')),
                ('google', models.CharField(blank=True, max_length=200, null=True, verbose_name='G+ link')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_team', to='base.about')),
            ],
            options={
                'verbose_name': 'Team Info',
                'verbose_name_plural': 'Teams Info',
            },
        ),
        migrations.CreateModel(
            name='ServicesTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Avator')),
                ('head_service', models.CharField(max_length=120, verbose_name='Service Head')),
                ('text_service', models.TextField(verbose_name='Text Service')),
                ('servicehead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tools', to='base.services')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head1', models.CharField(max_length=200, verbose_name='Head 1')),
                ('head2', models.CharField(max_length=200, verbose_name='Head 2')),
                ('head2_text', models.CharField(blank=True, max_length=120, null=True, verbose_name='Text Head 2')),
                ('banner', models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Image')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_banner', to='base.header')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='AboutPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='About Picture')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_pic', to='base.about')),
            ],
            options={
                'verbose_name': 'Team Picture',
                'verbose_name_plural': 'Teams Pictures',
            },
        ),
    ]
