# Generated by Django 3.1.6 on 2021-02-21 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head1', models.CharField(max_length=120, verbose_name='Head 1')),
                ('head1_text', models.CharField(max_length=120, verbose_name='Text Head 1')),
                ('head2', models.CharField(max_length=200, verbose_name='Head 2')),
                ('head2_text', models.CharField(max_length=120, verbose_name='Text Head 2')),
                ('img', models.ImageField(upload_to='..\\media\\pictures', verbose_name='Image')),
                ('img_head', models.CharField(max_length=200, verbose_name='Image Head')),
                ('img_text', models.TextField(verbose_name='Image Text')),
                ('plain_text', models.TextField(verbose_name='Plain Text')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='ServiceHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head1', models.CharField(max_length=200, verbose_name='Head 1')),
                ('head2', models.CharField(max_length=200, verbose_name='Head 2')),
                ('proj_total', models.IntegerField(verbose_name='Total Projects')),
                ('proj_done', models.IntegerField(verbose_name='Projects Done')),
                ('img', models.ImageField(upload_to='..\\media\\pictures', verbose_name='Image')),
                ('img_head', models.CharField(max_length=200, verbose_name='Image Head')),
                ('img_text', models.TextField(verbose_name='Image Text')),
            ],
            options={
                'verbose_name': 'Service Page',
                'verbose_name_plural': 'Services Page',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.ImageField(upload_to='..\\media\\pictures', verbose_name='Avator')),
                ('head_service', models.CharField(max_length=120, verbose_name='Service Head')),
                ('text_service', models.TextField(verbose_name='Text Service')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='..\\media\\pictures\\profile', verbose_name='Profile Inmage')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('bio', models.CharField(max_length=200, verbose_name='Bio')),
                ('fb', models.CharField(max_length=200, verbose_name='Facebook link')),
                ('twitter', models.CharField(max_length=200, verbose_name='twitter link')),
                ('ln', models.CharField(max_length=200, verbose_name='LinkedIn link')),
                ('google', models.CharField(max_length=200, verbose_name='G+ link')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_team', to='base.about')),
            ],
            options={
                'verbose_name': 'Team Info',
                'verbose_name_plural': 'Teams Info',
            },
        ),
        migrations.CreateModel(
            name='AboutPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='..\\media\\pictures', verbose_name='About Picture')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_pic', to='base.about')),
            ],
            options={
                'verbose_name': 'Team Picture',
                'verbose_name_plural': 'Teams Pictures',
            },
        ),
    ]
