# Generated by Django 3.1.6 on 2021-02-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='fb',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook link'),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='google',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='G+ link'),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='ln',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn link'),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='twitter link'),
        ),
    ]
