# Generated by Django 3.1.6 on 2021-02-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210222_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(upload_to='../media/pictures', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='aboutpic',
            name='pic',
            field=models.ImageField(upload_to='../media/pictures', verbose_name='About Picture'),
        ),
        migrations.AlterField(
            model_name='servicehead',
            name='img',
            field=models.ImageField(upload_to='../media/pictures', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='services',
            name='avator',
            field=models.ImageField(upload_to='../media/pictures', verbose_name='Avator'),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='img',
            field=models.ImageField(upload_to='../media/pictures\\profile', verbose_name='Profile Inmage'),
        ),
    ]
