# Generated by Django 3.1.6 on 2021-02-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210222_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='head3',
            field=models.CharField(default=1, max_length=120, verbose_name='Head 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='head3_text',
            field=models.CharField(default='sds', max_length=120, verbose_name='Text Head 3'),
            preserve_default=False,
        ),
    ]
