# Generated by Django 3.1.6 on 2021-02-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210222_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='head1_text',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Text Head 1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='head2_text',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Text Head 2'),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='head3_text',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Text Head 3'),
        ),
    ]
