# Generated by Django 3.1.6 on 2021-02-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210222_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminfo',
            name='head3',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='head3_text',
        ),
        migrations.AddField(
            model_name='about',
            name='head3',
            field=models.CharField(default=1, max_length=120, verbose_name='Head 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='head3_text',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Text Head 3'),
        ),
    ]
