# Generated by Django 3.1.7 on 2021-02-25 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210222_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='servicehead',
            field=models.ForeignKey(default=444, on_delete=django.db.models.deletion.CASCADE, related_name='service_tools', to='base.servicehead'),
            preserve_default=False,
        ),
    ]
