# Generated by Django 3.1.7 on 2021-02-25 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_services_servicehead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.ImageField(upload_to='../media/pictures', verbose_name='Avator')),
                ('head_service', models.CharField(max_length=120, verbose_name='Service Head')),
                ('text_service', models.TextField(verbose_name='Text Service')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Service Page', 'verbose_name_plural': 'Services Page'},
        ),
        migrations.RemoveField(
            model_name='services',
            name='avator',
        ),
        migrations.RemoveField(
            model_name='services',
            name='head_service',
        ),
        migrations.RemoveField(
            model_name='services',
            name='servicehead',
        ),
        migrations.RemoveField(
            model_name='services',
            name='status',
        ),
        migrations.RemoveField(
            model_name='services',
            name='text_service',
        ),
        migrations.AddField(
            model_name='services',
            name='head1',
            field=models.CharField(default=515, max_length=200, verbose_name='Head 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='head2',
            field=models.CharField(default=454, max_length=200, verbose_name='Head 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='img',
            field=models.ImageField(default=3246, upload_to='../media/pictures', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='img_head',
            field=models.CharField(default=6546, max_length=200, verbose_name='Image Head'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='img_text',
            field=models.TextField(default=34645, verbose_name='Image Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='proj_done',
            field=models.IntegerField(default=136, verbose_name='Projects Done'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='proj_total',
            field=models.IntegerField(default=231663, verbose_name='Total Projects'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ServiceHead',
        ),
        migrations.AddField(
            model_name='servicestools',
            name='servicehead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tools', to='base.services'),
        ),
    ]
