# Generated by Django 3.1.7 on 2021-02-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_services_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='servicestools',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status'),
        ),
    ]
