# Generated by Django 3.1.7 on 2021-02-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210225_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicestools',
            name='status',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='status',
        ),
    ]
