# Generated by Django 3.1.7 on 2021-02-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20210225_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='head2_text',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Text Head 2'),
        ),
    ]
