# Generated by Django 3.1.7 on 2021-02-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_contact_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone')),
                ('head', models.CharField(max_length=200, verbose_name='Contact Us Head')),
                ('logo', models.ImageField(upload_to='../media/pictures/logo', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Footer Control',
                'verbose_name_plural': 'Footer Control',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='../media/pictures/logo', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Header Control',
                'verbose_name_plural': 'Header Control',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact us', 'verbose_name_plural': 'Contact us'},
        ),
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(upload_to='../media/pictures/service', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='img',
            field=models.ImageField(upload_to='../media/pictures/profile', verbose_name='Profile Inmage'),
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='../media/pictures/banner', verbose_name='Image')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_banner', to='base.header')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
