# Generated by Django 3.1.7 on 2021-02-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20210228_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='header',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status'),
        ),
    ]
