# Generated by Django 3.1.7 on 2021-02-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20210228_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=60, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='header',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=60, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='services',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=60, verbose_name='Status'),
        ),
    ]
