# Generated by Django 3.1.7 on 2021-02-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20210228_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='fb',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook link'),
        ),
        migrations.AddField(
            model_name='footer',
            name='google',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='G+ link'),
        ),
        migrations.AddField(
            model_name='footer',
            name='ln',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn link'),
        ),
        migrations.AddField(
            model_name='footer',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='twitter link'),
        ),
    ]
