# Generated by Django 3.1.7 on 2021-02-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20210228_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Newsletters',
                'verbose_name_plural': 'Newsletters',
            },
        ),
    ]
