# Generated by Django 3.1.7 on 2021-02-28 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_newsletters'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletters',
            name='joindate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Join Date'),
            preserve_default=False,
        ),
    ]
