# Generated by Django 3.1.7 on 2021-02-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_newsletters_joindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='head1',
            field=models.CharField(default=545, max_length=200, verbose_name='Head 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banners',
            name='head2',
            field=models.CharField(default=5466, max_length=200, verbose_name='Head 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banners',
            name='head2_text',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Text Head 2'),
        ),
    ]
