# Generated by Django 3.1.7 on 2021-03-01 19:00

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20210228_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='aboutpic',
            name='pic',
            field=models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='About Picture'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='banner',
            field=models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='logo',
            field=models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='header',
            name='logo',
            field=models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='servicestools',
            name='avator',
            field=models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Avator'),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='img',
            field=models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Profile Inmage'),
        ),
    ]
