# Generated by Django 3.1.7 on 2021-03-03 19:19

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20210301_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='logo',
            field=models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='header',
            name='logo',
            field=models.ImageField(upload_to=base.models.get_img_upload_path, verbose_name='Logo'),
        ),
    ]
